[project]
name = "the-purge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Piotr Zakrzewski", email = "1050269+PiotrZakrzewski@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []
